{
 "title": "Span Metrics",
 "description": "SPM using Generated RED (Request, Error, Duration) Spanmetrics",
 "tags": [
  "otel",
  "traces",
  "spanmetrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traces_span_metrics_calls_total,service_name)"
    }
   },
   {
    "name": "kind",
    "query": {
     "query": "label_values(traces_span_metrics_calls_total,span_kind)"
    }
   },
   {
    "name": "operation",
    "query": {
     "query": "label_values(traces_span_metrics_calls_total{service_name=\"$service\", span_kind=\"$kind\"},span_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(.75, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(.50, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{service_name=\"$service\"}[$__rate_interval]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(traces_span_metrics_calls_total{service_name=\"$service\", status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval])) / sum(rate(traces_span_metrics_calls_total{service_name=\"$service\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Cache hits (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(traces_span_metrics_calls_total{service_name=\"$service\", cache_hit=\"true\"}[$__rate_interval])) / sum(rate(traces_span_metrics_calls_total{service_name=\"$service\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "Cache hit ratio"
    }
   ]
  },
  {
   "title": "Average memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_usage_bytes{service_name=\"$service\",operation=\"$operation\"}",
     "legendFormat": "memory usage"
    }
   ]
  },
  { "title": "$operation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "operation" },
  {
   "title": "P95 Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service\",span_name=\"${operation:raw}\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{service_name=\"$service\", span_name=\"${operation:raw}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(traces_span_metrics_calls_total{service_name=\"$service\", span_name=\"${operation:raw}\", status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval])) / sum(rate(traces_span_metrics_calls_total{service_name=\"$service\", span_name=\"${operation:raw}\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hits (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(traces_span_metrics_calls_total{service_name=\"$service\", span_name=\"${operation:raw}\", cache_hit=\"true\"}[$__rate_interval])) / sum(rate(traces_span_metrics_calls_total{service_name=\"$service\", span_name=\"${operation:raw}\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average memory usage per request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage_bytes{service_name=\"$service\",operation=\"$operation\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}